# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('id_number', models.IntegerField(verbose_name='Identification number')),
                ('email', models.EmailField(max_length=254)),
                ('temp_pass', models.CharField(max_length=40)),
                ('is_activated', models.BooleanField(default=False, verbose_name='Active')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
