# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(unique=True, verbose_name='Identification number'),
        ),
    ]
