# -*- coding: utf-8 -*-

# Generated by Django 1.9.4 on 2016-03-26 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0003_auto_20160326_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LoginApp.Client')),
            ],
            bases=('LoginApp.client',),
        ),
    ]
