# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0004_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name_plural': 'Staff'},
        ),
    ]
