# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0006_client_study_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='study_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.StudyLine'),
        ),
    ]
