# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
        ('LoginApp', '0007_auto_20160327_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='study_line',
        ),
        migrations.AddField(
            model_name='student',
            name='study_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.StudyLine'),
        ),
    ]
