# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0009_auto_20160327_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LoginApp.Client')),
                ('id_number', models.IntegerField(unique=True, verbose_name='Identification number')),
            ],
            bases=('LoginApp.client',),
        ),
    ]
