# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0005_auto_20160327_2209'),
        ('LoginApp', '0010_teacher'),
    ]

    operations = [
    ]
