# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0011_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id_number',
        ),
    ]
