# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0015_auto_20160410_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
