# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0006_auto_20160410_1633'),
        ('LoginApp', '0016_remove_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.StudyGroup'),
        ),
    ]
