# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0017_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='study_line',
        ),
    ]
