# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0019_chiefofdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='chiefofdepartment',
            name='department',
            field=models.CharField(choices=[('Informatics', 'Informatics'), ('Mathematics', 'Mathematics'), ('Mathematics & Informatics', 'Mathematics & Informatics')], max_length=50, null=True, unique=True),
        ),
    ]
