# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0020_chiefofdepartment_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentYearState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Current Year')),
                ('semester', models.IntegerField(verbose_name='Current Semester')),
                ('crtState', models.CharField(choices=[('First Semester going on', 'First Semester going on'), ('Second semester going on', 'Second semester going on'), ('Proposing optionals going on', 'Proposing optionals going on'), ('Optional package building going on', 'Optional package building going on'), ('Contract signing going on', 'Contract signing going on')], max_length=50, verbose_name='Current State')),
                ('oldState', models.CharField(choices=[('First Semester going on', 'First Semester going on'), ('Second semester going on', 'Second semester going on'), ('Proposing optionals going on', 'Proposing optionals going on'), ('Optional package building going on', 'Optional package building going on'), ('Contract signing going on', 'Contract signing going on')], max_length=50, null=True, verbose_name='Current State')),
            ],
        ),
    ]
