# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0021_currentyearstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currentyearstate',
            options={'verbose_name_plural': 'Current year state'},
        ),
    ]
