# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0022_auto_20160515_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_enrolled',
            field=models.BooleanField(default=True, verbose_name='Currently enrolled'),
        ),
    ]
