# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0023_student_is_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentyearstate',
            name='oldState',
            field=models.CharField(choices=[('First Semester going on', 'First Semester going on'), ('Second semester going on', 'Second semester going on'), ('Proposing optionals going on', 'Proposing optionals going on'), ('Optional package building going on', 'Optional package building going on'), ('Contract signing going on', 'Contract signing going on')], max_length=50, null=True, verbose_name='Old State'),
        ),
    ]
