# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 10:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0010_auto_20160410_1335'),
        ('LoginApp', '0013_auto_20160410_1335'),
        ('StudentApp', '0002_auto_20160328_0524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyLine',
        ),
    ]
