# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentApp', '0003_delete_studyline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Group Number')),
                ('year', models.DateField()),
                ('study_line', models.CharField(choices=[('Informatics', 'Informatics'), ('Mathematics', 'Mathematics'), ('Mathematics & Informatics', 'Mathematics & Informatics')], max_length=50)),
            ],
        ),
    ]
