# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_auto_20160410_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='StudyGroup',
        ),
    ]
