# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StudentApp', '0001_initial'),
        ('LoginApp', '0010_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('study_line', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StudentApp.StudyLine')),
                ('teacher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LoginApp.Teacher')),
            ],
        ),
    ]
