# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0010_teacher'),
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginApp.Student')),
            ],
        ),
    ]
