# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.Course', unique=True),
        ),
    ]
