# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0010_auto_20160410_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Year'),
        ),
    ]
