# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0011_course_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalCourse',
            fields=[
                ('course_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='TeacherApp.Course')),
            ],
            bases=('TeacherApp.course',),
        ),
    ]
