# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0012_optionalcourse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('name', 'teacher', 'study_line', 'year')]),
        ),
    ]
