# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0013_auto_20160411_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_number', models.IntegerField()),
                ('optional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.OptionalCourse')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='optionalpackage',
            unique_together=set([('package_number', 'optional')]),
        ),
    ]
