# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0014_auto_20160420_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_credits',
            field=models.IntegerField(default=6, verbose_name='Number of credits'),
        ),
    ]
