# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0015_course_number_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageToOptionals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.OptionalCourse')),
            ],
        ),
        migrations.AddField(
            model_name='optionalpackage',
            name='department',
            field=models.CharField(choices=[('Informatics', 'Informatics'), ('Mathematics', 'Mathematics'), ('Mathematics & Informatics', 'Mathematics & Informatics')], default=('Informatics', 'Informatics'), max_length=50),
        ),
        migrations.AddField(
            model_name='optionalpackage',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='optionalpackage',
            name='year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=1, verbose_name='Year'),
        ),
        migrations.AlterUniqueTogether(
            name='optionalpackage',
            unique_together=set([]),
        ),
        migrations.AddField(
            model_name='packagetooptionals',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.OptionalPackage'),
        ),
        migrations.RemoveField(
            model_name='optionalpackage',
            name='optional',
        ),
        migrations.RemoveField(
            model_name='optionalpackage',
            name='package_number',
        ),
    ]
