# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0016_auto_20160424_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalpackage',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
