# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0020_chiefofdepartment_department'),
        ('TeacherApp', '0016_auto_20160424_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.IntegerField(verbose_name='Course preference')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.OptionalCourse')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.OptionalPackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoginApp.Student')),
            ],
        ),
    ]
