# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0017_auto_20160514_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionalpackage',
            name='name',
            field=models.CharField(default='CO0', max_length=30, unique=True),
        ),
    ]
