# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0018_auto_20160514_1924'),
        ('TeacherApp', '0017_studentoptions'),
    ]

    operations = [
    ]
