# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0021_auto_20160515_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_year',
            field=models.IntegerField(default=2014, verbose_name='Course academic year'),
        ),
        migrations.AddField(
            model_name='optionalpackage',
            name='academic_year',
            field=models.IntegerField(default=2014, verbose_name='Package academic year'),
        ),
    ]
