# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-15 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0023_studentassignedcourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignedcourses',
            name='year',
            field=models.IntegerField(verbose_name='Academic year'),
        ),
    ]
