# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0024_auto_20160515_2008'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set([('name', 'teacher', 'study_line', 'year', 'academic_year')]),
        ),
    ]
