# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0006_auto_20160410_1633'),
        ('TeacherApp', '0024_auto_20160515_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examination Date', models.DateField()),
                ('Reexamination Date', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeacherApp.Course')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.StudyGroup')),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='second_date',
            field=models.BooleanField(default=False),
        ),
    ]
