# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0025_auto_20160529_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examinationperiods',
            old_name='Course',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='examinationperiods',
            old_name='Group',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='examinationperiods',
            name='Examination Date',
        ),
        migrations.RemoveField(
            model_name='examinationperiods',
            name='Reexamination Date',
        ),
        migrations.AddField(
            model_name='examinationperiods',
            name='exam_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 29, 17, 49, 15, 422167, tzinfo=utc), verbose_name='Examination Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examinationperiods',
            name='reexam_date',
            field=models.DateField(default=datetime.datetime(2016, 5, 29, 17, 49, 24, 680114, tzinfo=utc), verbose_name='Reexamination Date'),
            preserve_default=False,
        ),
    ]
