# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0026_auto_20160529_2049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExaminationPeriods',
            new_name='ExaminationPeriod',
        ),
    ]
