# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-29 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0027_auto_20160529_2051'),
        ('TeacherApp', '0025_auto_20160529_2044'),
    ]

    operations = [
    ]
